### PR TITLE
[Matrix] API update

### PR DESCRIPTION
**Pull request by AlwinEsch**
API related to xbmc/xbmc#17438 (DEMUX_PACKET not used there)

### CODE REVIEW

**Comment by AlwinEsch** [comment]
The request on Kodi comes in 1-2 days in and update also here needed.

**Comment by AlwinEsch** [comment]
Request in Kodi is in :smile:

**Comment by flubshi** [comment]
Thx for creating the release! :)

**Comment by AlwinEsch** [comment]
Yeah, if nothing goes wrong was that the last API related change within Kodi 19 Matrix.

**Pull request merged**
