### PR TITLE
Implement EPG tag preview images

### PR DESCRIPTION
**Pull request by flubshi**
Add preview images to EPG tags

## Screenshots

**Before:**

before

**After:**

after

### CODE REVIEW

**Review by ksooo — DISMISSED** [review]
Nice. Please increase add-on minor number and add a changelog entry and we re ready to merge this.

**Comment by ksooo** [comment]
> Nice. Please increase add-on minor number and add a changelog entry and we re ready to merge this.

 Ooops. Wrong PR.

**Comment by puenktchen** [comment]
Why isn't it merged yet and will we get a backport to Matrix?

**Comment by ksooo** [comment]
> Why isn't it merged yet and 

 Because the PR submitter did not yet supply the request version bump and changelog. The PR is incomplete. 

> will we get a backport to Matrix?

If somebody opens the respective PR, yes.

**Comment by flubshi** [comment]
> Why isn't it merged yet and will we get a backport to Matrix?

No real reason. Had no time for testing. Compiling kodi right now, will test, backport and release soon.

**Pull request merged**
