### PR TITLE
Remove p8-platform dependency - v2.0.1

### PR DESCRIPTION
**Pull request by phunkyfish**
v2.0.1 
- Remove p8-platform dependency

### CODE REVIEW

**Comment by phunkyfish** [comment]
If you are ok with this PR please merge and release when you can. Ty!

**Comment by phunkyfish** [comment]
Hi, can you merge and release this please?

It is required as we move forward with the kodi 19 release plan. Thanks!

**Comment by flubshi** [comment]
Hi phunkyfish! Thx for your MR, I will merge & release soon!

**Comment by phunkyfish** [comment]
Thanks!!!

**Pull request merged**
