### PR TITLE
[debian] fix dependencies after 316c1a6

### PR DESCRIPTION
**Pull request by Rechi**

### CODE REVIEW

**Comment by Rechi** [comment]
You may want to release a new version, including this fix, so that Ubuntu PPA users can get your add-on.

**Comment by flubshi** [comment]
Done (bumped to 1.2.2). Thanks for this hint. I saw that you triggered jenkins build this morning: is there an easy way to figure out if ubntu ppa build/release succeeded? [Here](https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa/+index?batch=75&memo=525&start=525)?

**Comment by Rechi** [comment]
You are looking at the wrong PPA. The Matrix version of add-ons currently is currently uploaded to the Kodi Nightly Builds PPA, because that's the one containing a Kodi Matrix version.

It seems like Ubuntu packaging was always broken. The add-on requires RapidJSON (>= 1.0.2), but `rapidjson-dev (>= 1.0.2)` is also missing in `Build-Depends`.

**Comment by flubshi** [comment]
Seems to build now for Bionic and newer. A proper rapidjson version is not available in Xenial repos, thus build fails.

**Comment by Rechi** [comment]
You are inconsistent with requiring a minimum RapidJSON version.

https://github.com/flubshi/pvr.waipu/blob/07fa7279e4e58d054e3a2a15cf12c74b228f4f74/CMakeLists.txt#L8
https://github.com/flubshi/pvr.waipu/blob/7b93ce857f8f47f4cf7a980060b8fb82d8f6e1cf/FindRapidJSON.cmake#L13
https://github.com/flubshi/pvr.waipu/blob/7b93ce857f8f47f4cf7a980060b8fb82d8f6e1cf/FindRapidJSON.cmake#L22

Depending on which one is your real minimum required version, it could also built for Upuntu Xenial.

**Pull request merged**
